//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int BookId { get; set; }
        public string Ttile { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public string ISBN { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> copies { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
